"""empty message

Revision ID: 011dfde256a4
Revises: 60d7e5e5a3d0
Create Date: 2020-04-20 13:31:16.356147

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '011dfde256a4'
down_revision = '60d7e5e5a3d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ViewPoint',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_ViewPoint_ID'), 'ViewPoint', ['ID'], unique=False)
    op.drop_index('ix_VeiwPoint_ID', table_name='VeiwPoint')
    op.drop_table('VeiwPoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VeiwPoint',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"VeiwPoint_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='VeiwPoint_pkey')
    )
    op.create_index('ix_VeiwPoint_ID', 'VeiwPoint', ['ID'], unique=False)
    op.drop_index(op.f('ix_ViewPoint_ID'), table_name='ViewPoint')
    op.drop_table('ViewPoint')
    # ### end Alembic commands ###
