"""empty message

Revision ID: 25ec474b545a
Revises: 920af05f380b
Create Date: 2020-04-22 13:25:45.946597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ec474b545a'
down_revision = '920af05f380b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ViewPoint', sa.Column('rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ViewPoint', 'rating')
    # ### end Alembic commands ###
