"""empty message

Revision ID: 4b5758230318
Revises: a72bc267aef4
Create Date: 2020-04-25 18:01:16.026513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b5758230318'
down_revision = 'a72bc267aef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Model_ID', table_name='Model')
    op.drop_table('Model')
    op.drop_column('ViewPoint', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ViewPoint', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('Model',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"Model_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('startdate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enddate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='Model_pkey')
    )
    op.create_index('ix_Model_ID', 'Model', ['ID'], unique=False)
    # ### end Alembic commands ###
