"""empty message

Revision ID: 4fc3d30697ce
Revises: 25ec474b545a
Create Date: 2020-04-22 13:40:06.634099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc3d30697ce'
down_revision = '25ec474b545a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ViewPoint', sa.Column('numberOfRatings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ViewPoint', 'numberOfRatings')
    # ### end Alembic commands ###
