"""empty message

Revision ID: 82025de14996
Revises: cb7bc5c43a7d
Create Date: 2020-04-19 13:16:14.066841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82025de14996'
down_revision = 'cb7bc5c43a7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('VeiwPoint', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('VeiwPoint', 'image_name')
    # ### end Alembic commands ###
