"""empty message

Revision ID: 8722de3dd827
Revises: de6afd828480
Create Date: 2020-04-12 23:45:58.524546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8722de3dd827'
down_revision = 'de6afd828480'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiwPoint',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_veiwPoint_ID'), 'veiwPoint', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veiwPoint_ID'), table_name='veiwPoint')
    op.drop_table('veiwPoint')
    # ### end Alembic commands ###
