"""empty message

Revision ID: a72bc267aef4
Revises: 4fc3d30697ce
Create Date: 2020-04-23 15:01:11.051467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a72bc267aef4'
down_revision = '4fc3d30697ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ViewPoint', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ViewPoint', 'type')
    # ### end Alembic commands ###
