"""empty message

Revision ID: cb7bc5c43a7d
Revises: 8722de3dd827
Create Date: 2020-04-13 14:10:03.365495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb7bc5c43a7d'
down_revision = '8722de3dd827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VeiwPoint',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_VeiwPoint_ID'), 'VeiwPoint', ['ID'], unique=False)
    op.drop_index('ix_veiwPoint_ID', table_name='veiwPoint')
    op.drop_table('veiwPoint')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiwPoint',
    sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"veiwPoint_ID_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('long', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ID', name='veiwPoint_pkey')
    )
    op.create_index('ix_veiwPoint_ID', 'veiwPoint', ['ID'], unique=False)
    op.drop_index(op.f('ix_VeiwPoint_ID'), table_name='VeiwPoint')
    op.drop_table('VeiwPoint')
    # ### end Alembic commands ###
