"""empty message

Revision ID: ccb5cfad6e69
Revises: 
Create Date: 2020-02-28 14:10:14.351428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb5cfad6e69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Model',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('startdate', sa.TIMESTAMP(), nullable=True),
    sa.Column('enddate', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Model_ID'), 'Model', ['ID'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Model_ID'), table_name='Model')
    op.drop_table('Model')
    # ### end Alembic commands ###
