"""empty message

Revision ID: f98281c023b9
Revises: 4b5758230318
Create Date: 2020-04-26 13:07:03.419955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f98281c023b9'
down_revision = '4b5758230318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ViewPoint', sa.Column('altitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ViewPoint', 'altitude')
    # ### end Alembic commands ###
